import type { Metadata } from 'next'
import { IBM_Plex_Sans, IBM_Plex_Sans_KR } from 'next/font/google'
import './globals.css'

const ibmPlexSans = IBM_Plex_Sans({
  variable: '--font-ibm-plex-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

const ibmPlexSansKr = IBM_Plex_Sans_KR({
  variable: '--font-ibm-plex-sans-kr',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <body className={`${ibmPlexSans.variable} ${ibmPlexSansKr.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
